import numpy as np

def gradient1_order2_dx(array: np.ndarray, dx: np.floating)-> np.ndarray: ...

def gradient1_order2_var_x(array: np.ndarray, x: np.ndarray)-> np.ndarray: ...

def gradient2_order2_dx(array: np.ndarray, dx: np.floating)-> np.ndarray: ...

def gradient2_order2_var_x(array: np.ndarray, x: np.ndarray)-> np.ndarray: ...
